spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: erik
    password: erikpassword
    driver-class-name: org.postgresql.Driver
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect